# Generated by Django 3.2 on 2021-04-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_rename_good_item_gooditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gooditem',
            old_name='title',
            new_name='Товар',
        ),
    ]
