# Generated by Django 3.2 on 2021-04-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Good_Item',
        ),
    ]
