# Generated by Django 3.2 on 2021-04-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_good_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Good_Item',
            new_name='GoodItem',
        ),
    ]
