# Generated by Django 3.2 on 2021-04-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_rename_title_gooditem_товар'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gooditem',
            old_name='Товар',
            new_name='title',
        ),
    ]
